find_path(LIBSPNAV_INCLUDE_DIR /usr/local/include)
find_library(LIBSPNAV_LIBRARY /usr/local/lib)

if (LIBSPNAV_INCLUDE_DIR AND LIBSPNAV_LIBRARY)
    set(LIBSPNAV_FOUND TRUE)
endif (LIBSPNAV_INCLUDE_DIR AND LIBSPNAV_LIBRARY)
